### PR TITLE
Makes environment check errors more generic than Debian

### PR DESCRIPTION
**Pull request by b-m-f**

### CODE REVIEW

**Comment by lord** [comment]
Agreed making it not debian-specific would be good. But maybe we can instead figure out and insert the appropriate command based on the operating system? We're already detecting and putting the OS information in the questionable location of `process.detailedos`. Would be nice for users to be able to copy-paste a command from the error message to fix.

**Comment by b-m-f** [comment]
Makes sense. Let me see if I can add Fedora support. Will update the PR

**Comment by b-m-f** [comment]
https://github.com/lord/wargo/pull/7/commits/de1654576903ebdef023fd8197b208dac475c7b8
This one implements the logic. Can not check it on Mac, but I guess `darwin` should be the correct key.


In the other commits I have added eslint and prettier to have the code consistent. I have added disable comments where I was not sure.

**Comment by lord** [comment]
Looking pretty good! It looks like `distro` is `null` [on macOS](https://github.com/retrohacker/getos/blob/ba595b2167003d85982b0d6cf7aee2498ec63000/index.js#L19-L23) as well as on unknown linuxes in the latest version of wargo (about to merge the `fix6` branch). Maybe instead of a whole new file and eslint, we can just add a simple function `getInstallCmd(toolname)` and interpolate into the checks already in `setup.js`? Could even remove some redundancy between darwin + linux checks, we already got bit by a [bug](https://github.com/lord/wargo/commit/05f7932be379e944b446c9848670ed4850b8521d) where the check command was accidentally different between macOS and Linux. Thoughts?

**Pull request closed without merging**
